[phases.setup]
nixPkgs = [
    "python311",
    "postgresql",
    "gcc",
    "musl-dev",
    "libffi-dev",
    "openssl-dev",
    "zlib-dev",
    "jpeg-dev",
    "portaudio-dev"
]

[phases.build]
cmds = [
    "pip install -r requirements.txt",
    "python manage.py collectstatic --noinput",
    "python manage.py migrate",
    "python manage.py init_admin"
]

[start]
cmd = "gunicorn pavilion_gemini.wsgi --bind 0.0.0.0:$PORT"
